#!/usr/bin/env python
# -*- coding: utf-8 -*-

### Import modules ###
import module.mylink as mylink
from statistics import mean, median, mode
import argparse
import random
import sys
import gzip
######################

# func
def csvdecompose( 
        inputfile, 
        column   , 
        delim    ,
        gzip     ,
        ):
    
    # prep
    column = column - 1

    # read file
    if (inputfile == None):
        inhandle = sys.stdin
        inputfile = "stdin.txt"
    else:
        inhandle = open(inputfile,'r')

    key2outhandle = {}
    
    for line in inhandle:
        
        key = line.split("\n")[0].split(delim)[column]

        if (key not in key2outhandle.keys()):

            if (gzip):
                key2outhandle[key] = gzip.open(".".join(inputfile.split(".")[:-1]+[key, inputfile.split(".")[-1], "gz"]), 'wt')   
            else: 
                key2outhandle[key] = open(".".join(inputfile.split(".")[:-1]+[key, inputfile.split(".")[-1]]), 'w')
        
        key2outhandle[key].write(line)
    
    inhandle.close()
    for key in key2outhandle.keys():
        key2outhandle[key].close()

# interface
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='csvdecompose', add_help=True)
    
    parser.add_argument(
        "-v", "--version",
        help="Print table rep version",
        action='store_true',
        default=False
        )

    parser.add_argument(
        "-i", "--input",
        help="Input file path",
        default=None
        )
    
    parser.add_argument(
        "-c", "--column",
        help="Choose 1 column as a key of file division",
        type=int,
        default=1
        )
    
    parser.add_argument(
        "-d", "--delimitter",
        help="Specify the delimitter",
        default="\t"
    )

    parser.add_argument(
        "-g", "--gzip",
        help="Gzip output files",
        action='store_true',
        default=False
    )


    # parse arguments
    args = parser.parse_args()

    # execute main_function()
    csvdecompose( 
        inputfile    = args.input      , 
        column       = args.column     , 
        delim        = args.delimitter ,
        gzip         = args.gzip
        )