#!/usr/bin/env python
# -*- coding: utf-8 -*-

### Import modules ###
import argparse
import sys
import numpy as np
import pandas as pd
######################

# func
def m2sm( args ):

    inputfile = args.input
    delim     = args.delim

    # read a file

    if (inputfile == None):
        handle = sys.stdin
    else:
        handle = open(inputfile, 'r')  
        
    # format: 
    # \t<col name 1>\t<col name 2>\t<col name 3>...
    # <row name 1>\t<value 11>\t<row name value 12>...
    # <row name 2>\t<value 21>\t<row name value 22>...

    df = pd.read_table(handle, delimiter = delim, index_col=0)

    for row in df.index:
        for column in df.columns:
            value = df.loc[row, column]
            print(row, column, value, sep = delim) 

# interface
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='csvonehot', add_help=True)
    
    parser.add_argument(
        "-v", "--version",
        help="Print table rep version",
        action='store_true',
        default=False
        )

    parser.add_argument(
        "-i", "--input",
        help="Input file path",
        default=None
        )
    
    parser.add_argument(
        "-d", "--delim",
        help="delimitter between key and value",
        default="\t"
        )
        
    # parse arguments
    args = parser.parse_args()

    # execute main_function()
    m2sm( args )