#!/usr/bin/env python
# -*- coding: utf-8 -*-

### Import modules ###
import module.mylink as mylink
from statistics import mean, median, mode
import argparse
######################

# func
def csvonehot(inputfile, delim1="\t", delim2=";"):

    # read a file
    myhash_before = mylink.make_hash2(
        inputfile, 
        delim1=delim1, 
        delim2=delim2, 
        value_type="str"
        )

    # get the union of values
    value_set     = set()
    for key in myhash_before.keys():
        value_set = value_set | set(myhash_before[key])
    value_list    = list(value_set)

    # 
    myhash_after  = dict()
    for key in myhash_before.keys():
        value_set_of_the_key = set(myhash_before[key])
        one_hot_vector       = [0] * len(value_list)
        for i, value in enumerate(value_list):
            if(value in value_set_of_the_key):
                one_hot_vector[i] = 1
            else:
                one_hot_vector[i] = 0
        myhash_after[key]         = one_hot_vector
    
    mylink.export_hash(
        myhash_after, 
        delim=[delim1,delim2], 
        value_type="list"
        )

# interface
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='csvrep', add_help=True)
    
    parser.add_argument(
        "-v", "--version",
        help="Print table rep version",
        action='store_true',
        default=False
        )

    parser.add_argument(
        "-i", "--input",
        help="Input file path",
        default=None
        )
    
    parser.add_argument(
        "--delim1",
        help="delimitter between key and value",
        default="\t"
        )
    
    parser.add_argument(
        "--delim2",
        help="delimitter among values",
        default="\t"
        )
        
    # parse arguments
    args = parser.parse_args()

    # execute main_function()
    csvonehot(  
        inputfile = args.input ,
        delim1    = args.delim1,
        delim2    = args.delim2
    )