#!/usr/bin/env python
# -*- coding: utf-8 -*-

### Import modules ###
import module.mylink as mylink
from statistics import mean, median, mode
import argparse
import random
######################

# func
def csvtranspose(inputfile, delim="\t"):

    table_content=[]
    with open(inputfile, 'r') as handle:
        for line in handle:
            table_content.append(line.split("\n")[0].split(delim))
    for j in range(len(table_content[0])):
        for i in range(len(table_content)):
            if (i == len(table_content) - 1):
                print(table_content[i][j], end="\n")
            else:
                print(table_content[i][j], end=delim)

# interface
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='csvtranspose', add_help=True)
    
    parser.add_argument(
        "-v", "--version",
        help="Print csvtranspose version",
        action='store_true',
        default=False
        )

    parser.add_argument(
        "-i", "--input",
        help="Input file path",
        default=None
        )

    parser.add_argument(
        "-d", "--delimitter",
        help="Specify the delimitter",
        default="\t"
        )
    
    # parse arguments
    args = parser.parse_args()

    # execute main_function()
    csvtranspose( 
        inputfile    = args.input                    , 
        delim        = args.delimitter               ,
        )